spring:
    redis:
      #数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          #最大连接数
          max-active: 100
          #最大阻塞等待时间(负数表示没限制)
          max-wait: 100000ms
          #最大空闲
          max-idle: 10
          #最小空闲
          min-idle: 0
      #连接超时时间
      timeout: 10000s